language: node_js
node_js:
- '0.10'
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- npm install -g grunt-cli
install:
- npm install
- grunt pack --no-color
script:
- 'true'
git:
  submodules: false
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: eUmm52zfs68StxqUkPWuuNa85vBrlYmjuRw4FR8kZSyBWKkCySU8xuZVRpxLdqE3VRAsORsP2Ggf4UKqDM4BtTNl0lZGLeyT2OuL/9AB1r/IqzylLI2xAmibboLktFL4BQL8uqWnBkyYHSC0Ufv7C8poXdbyubLrSMuP9hRBy/0=
  file: travis/nativescript.tgz
  on:
    tags: true
    all_branches: true
- provider: npm
  email: tailsu@gmail.com
  api_key:
    secure: NL1DbE1q8tPqIYA4ixZqpvaDeYkPCnMst2/bB/fBcHsR8pqV+QxBCC0LE5GGhIzrFEBcnppsC1jIv9HWOezdNFPcBBF4zVUQzMWlrZSQ3EY1vWAqfKjgHiWRWd3hXu3gNR8SfqRHTn+VcmKhOWA6c9lgez41/BdJSE5Z3WupF+g=
  on:
    tags: true
    all_branches: true
