env:
  global:
  - DATE=$(date +%Y-%m-%d)
  - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
  - NATIVESCRIPT_SKIP_POSTINSTALL_TASKS=1
language: node_js
node_js:
- '4'
git:
  submodules: false
before_script:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- npm install grunt
- node_modules/.bin/grunt enableScripts:false
- npm install
- npm test
- node_modules/.bin/grunt enableScripts:true
script:
- node_modules/.bin/grunt lint
- node_modules/.bin/grunt pack --no-color
after_success:
- rm -rf s3-publish
- mkdir s3-publish
- cp nativescript*.tgz s3-publish/nativescript.tgz
before_deploy:
- node .travis/add-publishConfig.js next
deploy:
  matrix:
  - provider: s3
    bucket: nativescript-ci
    access_key_id: AKIAIYSWYOZRFLVKPCTQ
    secret_access_key:
      secure: HbAi6CiFoA2PsVpv/uT7obcfKXBeRqt0Arq3Wy2WgvAswnPrY9vkqWJb4e/NAo5XTzwe55Z8NhxAQXJAF+R0F3ZkD65TeQ1gptVgePLggOAsAeAw4eYY20YeGsTGJJ90V/O2yOHUKWOmVA19qkQin5GKIkXAlEIm4K/+SMefvic=
    skip_cleanup: true
    local-dir: "s3-publish"
    upload-dir: "build_result"
    on:
      all_branches: true
  - provider: npm
    skip_cleanup: true
    email: nativescript@telerik.com
    on:
      branch: master
    api_key: 
    secure: Ugq6m/y4P5gF15zffYzTKhusn1Csu3ymYLdD+yXgyK3hek9Ms5PKTz4MKgPinlViRCBoQV2fGh0JsCikawIpmQyD+M+FRDKlP2GcXPhFmSN1wVEloxTCwe7H6m7Kl9mo+MJOTS0BN7waCc6yTJBJPxo5nwFgz+DT2srIYndA2h4=
